language: minimal
os:
  - linux
  - windows
  - macos
stages:
  - reference
  - test

jobs:
  include:
    - stage: reference
      os: linux
      before_install: true
      before_script:
        - mkdir $HOME/stuff
        - touch $HOME/stuff
      before_cache:
        - mv $HOME/stuff stuff
      workspaces:
        create:
          name: base
          paths: stuff

workspaces:
  use: base

before_install:
  - ls -l
  - if [ -e stuff ]; then mv stuff $HOME/stuff; fi

script:
  - ls -ahl
  - ls -ahl $HOME
  - if [ -e $HOME/stuff ]; then ls -ahl $HOME/stuff; fi
  - touch $HOME/stuff/somestuff

